# Generated by Django 6.0.2 on 2026-02-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FixedExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=13)),
                ("payment_day", models.PositiveSmallIntegerField()),
                ("category", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("store_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="1~5점 사이의 중요도"
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True)),
                ("is_fixed_expense", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
