# Generated by Django 6.0.2 on 2026-02-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ai_feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
