# Generated by Django 6.0.2 on 2026-02-25 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_alter_asset_asset_type"),
        ("finance", "0003_transaction_ai_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="real_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="assets.asset",
            ),
        ),
    ]
