# Generated by Django 6.0.2 on 2026-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_transaction_real_date_alter_transaction_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category_middle",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[("income", "수입"), ("spending", "지출"), ("saving", "저축")],
                max_length=10,
            ),
        ),
    ]
