# Generated by Django 6.0.2 on 2026-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_transaction_category_middle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="guitar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category_middle",
            field=models.CharField(
                choices=[("necessity", "필요"), ("choice", "선택"), ("guitar", "기타")],
                max_length=20,
                null=True,
            ),
        ),
    ]
