# Generated by Django 6.0.2 on 2026-02-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_transaction_guitar_alter_transaction_category_middle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category_middle",
            field=models.CharField(
                choices=[("necessity", "필요"), ("choice", "선택"), ("guitar", "기타")],
                max_length=20,
            ),
        ),
    ]
