# Generated by Django 6.0.2 on 2026-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_alter_transaction_category_middle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="guitar",
            new_name="etc",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category_middle",
            field=models.CharField(
                choices=[("necessity", "필요"), ("choice", "선택"), ("etc", "기타")],
                max_length=20,
            ),
        ),
    ]
