# Generated by Django 6.0.2 on 2026-02-26 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("bank", "계좌"),
                            ("card", "신용카드"),
                            ("cash", "현금"),
                            ("giftcard", "선불카드"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("provider", models.CharField(blank=True, default="", max_length=100)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=13,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "display_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("encrypted_number", models.TextField(blank=True, default="")),
                ("is_saving_account", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
