# Generated by Django 6.0.2 on 2026-02-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("bank", "계좌"),
                            ("card", "신용카드"),
                            ("cash", "현금"),
                            ("gifcard", "선불카드"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=13),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
