# Generated by Django 6.0.2 on 2026-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("bank", "계좌"),
                    ("card", "신용카드"),
                    ("cash", "현금"),
                    ("giftcard", "선불카드"),
                ],
                max_length=10,
            ),
        ),
    ]
