# Generated by Django 6.0.2 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE assets_asset "
                        "ADD COLUMN IF NOT EXISTS is_saving_account boolean NOT NULL DEFAULT false"
                    ),
                    reverse_sql=(
                        "ALTER TABLE assets_asset "
                        "DROP COLUMN IF EXISTS is_saving_account"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="asset",
                    name="is_saving_account",
                    field=models.BooleanField(default=False),
                )
            ],
        ),
    ]
