# Generated by Django 6.0.2 on 2026-02-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_alter_asset_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_saving_account",
            field=models.BooleanField(default=False),
        ),
    ]
