# Generated by Django 6.0.2 on 2026-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_asset_is_saving_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="provider",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="asset",
            name="display_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="asset",
            name="encrypted_number",
            field=models.TextField(blank=True, default=""),
        ),
    ]
