# Generated by Django 6.0.2 on 2026-02-25 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_asset_provider_asset_display_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
