# Generated by Django 6.0.2 on 2026-02-25 08:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


def set_negative_balance_to_zero(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    Asset.objects.filter(balance__lt=0).update(balance=0)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_asset_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="balance",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=13,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RunPython(set_negative_balance_to_zero, noop_reverse),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(balance__gte=0),
                name="asset_balance_gte_0",
            ),
        ),
    ]
