# Generated by Django 6.0.2 on 2026-02-26 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_asset_is_saving_account"),
        ("assets", "0007_asset_updated_at_and_constraints"),
    ]

    operations = []
