# Generated by Django 6.0.2 on 2026-02-26 05:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MissionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "target_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                    ),
                ),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "진행 중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "포기"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "snapshot_saved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="완료·포기 시점의 저축 금액 스냅샷. 진행 중엔 null.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="완료 또는 포기 처리된 시각.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mission_goal",
                "ordering": ["-created_at"],
            },
        ),
    ]
