# Generated by Django 6.0.2 on 2026-02-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoalAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="goal_albums/")),
                ("child_memo", models.TextField(blank=True)),
                ("parent_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MissionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("target_price", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "saved_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_PROGRESS", "진행 중"), ("COMPLETED", "완료")],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
