# Generated by Django 6.0.2 on 2026-02-26 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("missions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="missiongoal",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="missiongoal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("child",),
                name="uniq_in_progress_goal_per_child",
            ),
        ),
        migrations.AddConstraint(
            model_name="missiongoal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "IN_PROGRESS"), _negated=True),
                    models.Q(
                        ("snapshot_saved_amount__isnull", True),
                        ("completed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_in_progress_fields_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="missiongoal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "IN_PROGRESS"),
                    models.Q(
                        ("snapshot_saved_amount__isnull", False),
                        ("completed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chk_done_fields_not_null",
            ),
        ),
    ]
