# Generated by Django 6.0.2 on 2026-02-26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoalAlbum",
        ),
        migrations.RemoveField(
            model_name="missiongoal",
            name="saved_amount",
        ),
        migrations.AddField(
            model_name="missiongoal",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="완료 또는 포기 처리된 시각.", null=True
            ),
        ),
        migrations.AddField(
            model_name="missiongoal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="missiongoal",
            name="snapshot_saved_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="완료·포기 시점의 저축 금액 스냅샷. 진행 중엔 null.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="missiongoal",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="missiongoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "진행 중"),
                    ("COMPLETED", "완료"),
                    ("CANCELLED", "포기"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="missiongoal",
            table="mission_goal",
        ),
        migrations.AddConstraint(
            model_name="missiongoal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("child",),
                name="uniq_in_progress_goal_per_child",
            ),
        ),
        migrations.AddConstraint(
            model_name="missiongoal",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(status="IN_PROGRESS")
                    | (
                        models.Q(snapshot_saved_amount__isnull=True)
                        & models.Q(completed_at__isnull=True)
                    )
                ),
                name="chk_in_progress_fields_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="missiongoal",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(status="IN_PROGRESS")
                    | (
                        models.Q(snapshot_saved_amount__isnull=False)
                        & models.Q(completed_at__isnull=False)
                    )
                ),
                name="chk_done_fields_not_null",
            ),
        ),
    ]
