# Generated by Django 6.0.2 on 2026-02-25 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoalAlbum",
        ),
    ]
