# Generated by Django 6.0.2 on 2026-02-26 02:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0003_missiongoal_snapshot_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missiongoal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="missiongoal",
            name="target_price",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
            ),
        ),
    ]
