# Generated by Django 6.0.2 on 2026-02-26 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0003_delete_goalalbum"),
        ("missions", "0004_alter_missiongoal_options_and_more"),
    ]

    operations = []
